### ISSUE TITLE
Hard-coded account_id might be an issue in multi-account environments

### ISSUE THREAD

**Issue by gokulpch** [keikoproj/iam-manager#24]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request/Question

**What happened**:
Is a hard-coded account_id needed which might change in a multi-org setting having clusters across accounts. In this case the user has to change the parameter for every cluster and this might not be the case if there is a global pipeline deploying to multiple clusters.

**What you expected to happen**:
STS caller identity can get the account id based on the master-iam-role. With this there is no need to set the account-id.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy application in a different account than the one mentioned in the configmap. Role creation fails.

**Anything else we need to know?**:

properties.go:

```
//LoadProperties function loads properties from various sources
func LoadProperties(ctx context.Context, kClient *k8s.Client, ns string, cmName string) (*Properties, error) {
	log := log.Logger(ctx, "config", "LoadProperties")
	log.WithValues("namespace", ns)
	log.Info("loading properties")
	stsClient := sts.New(session.New())
	callerIdentity, err := stsClient.GetCallerIdentity(&sts.GetCallerIdentityInput{})
	if err != nil {
		log.Info("error getting caller idenity client. err: %v", err)
		return nil, err
	}
	return &Properties{
		AWSAccountId: *callerIdentity.Account,
	}, nil
}
```

**Environment**:
- iam-manager version
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:

```
- controller logs:
```
$ kubectl logs <iam-manager>
```

**Comment by mnkg561** [comment]
@gokulpch Good idea. Please feel free to create a PR
