### ISSUE TITLE
Bug: Your "keikoproj/iam-manager:latest" image is bad

### ISSUE THREAD

**Issue by diranged** [keikoproj/iam-manager#63]
**Is this a BUG REPORT or FEATURE REQUEST?**:

This is a bug report

**What happened**:

The `keikoproj/iam-manager:latest` image is referenced in the various resource templates for this project. This image is bad. It comes up and runs, but it appears to be based off someone's custom branch (perhaps your own?) that has a whole bunch of things hard coded in it. It was trying to create IAM roles and policies with hard-coded AWS Account IDs. When we initially tested it we were actually sure it was a trojan horse.

I _strongly_ recommend you take that image down.

**How to reproduce it (as minimally and precisely as possible)**:

Pull down the image and run it in a new AWS account id..watch it fail.

```
MalformedPolicyDocument: Invalid principal in policy: "AWS":"arn:aws:iam::000065563193:role/masters.ops-prim-ppd.cluster.k8s.local"
```

**Comment by mnkg561** [comment]
Thanks.. This was probably from latest push. we will fix it ASAP
