### ISSUE TITLE
ServiceAccounts should be annotated with sts-regional-endpoints for HA

### ISSUE THREAD

**Issue by vgunapati** [keikoproj/iam-manager#89]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
**What happened**:

HA for IAM: EKS recommends not using the global endpoint (us-east-1) and instead using the regional endpoint. ServiceAccounts should be annotated with `eks.amazonaws.com/sts-regional-endpoints: "true"`, in order to reach out to the regional IRSA, than the global endpoint. Details at
https://github.com/aws/amazon-eks-pod-identity-webhook#aws_sts_regional_endpoints-injection
We need to enable this for all service accounts. 

**What you expected to happen**:
when a ServiceAccounts is annotated by the IAM manager with Role, we should also add `eks.amazonaws.com/sts-regional-endpoints: "true"`

**Comment by vgunapati** [comment]
This is a minor change to ServiceAccount you can include it in #87 if you want, if not we can do it after #87

**Comment by nrosenberg1** [comment]
@diranged since this is a small change and will be a breaking issue if default global endpoint us-east-1 goes down, we are going to get this change in first. There are also several comments on #87 please address those as well.
